### ISSUE TITLE
Select by name doesn't work

### ISSUE THREAD

**Issue by pixtur** [canisminor1990/sketch-select#11]
Hi,

I have a number of groups, each containing a number of shapes, like this:

```
Group 12312
   Stroke__
   Triangle__
Group 12313
   Stroke__
   Triangle__
```

Selecting the Triangle__ shape and using sketch-select by name doesn't to anything for me. What is the expected result?

BR,
tom

**Comment by rodnem** [comment]
I encounter this too but have you try to keep AllTypes activ ?
For me it works

**Comment by canisminor1990** [comment]
Fixed
