### ISSUE TITLE
Option to select by partial text match

### ISSUE THREAD

**Issue by jimhare** [canisminor1990/sketch-select#12]
Often textual layer properties (i.e. LayerName, TextString) use _similar_ labelling rather than _exact_ labelling. If I have SpecialNamedLayer1, SpecialNamedLayer2, etc., I want to be able to select them all.

An option to choose a portion of the selected layers' text would be great.

The layer list filtering can achieve a similar effect, but once filtered, it's not always easy to actually _select_ all the matches (especially when they're nested at different levels or hidden).

**Comment by Joshuwar** [comment]
I agree, an option for _partial_ layer name matching would be awesome (especially since Layer Tools seems to have gone quiet)

**Comment by canisminor1990** [comment]
Done
