### ISSUE TITLE
No selections being made

### ISSUE THREAD

**Issue by davidsanders** [canisminor1990/sketch-select#14]
Running latest Sketch (46.2) and none of the selection options make a valid selection or any selection at all.

The old version, before the new UI, worked wonderfully. :(

**Comment by RaphyRaph** [comment]
this plugin * never * works. I don't understand.

**Comment by hoofdletterj** [comment]
yup.. same here. doesn't select anything. v 48.2

**Comment by davidsanders** [comment]
This seems to be working again as of the latest version of sketch (49) and select (3.0.1)
