### ISSUE TITLE
Select a symbol

### ISSUE THREAD

**Issue by mischugo** [canisminor1990/sketch-select#4]
Whats about the feature to select all symbols of a document.

I have some pages in a document with tons pf symbols, and i would like to select them all for detaching :-)

Best!

**Comment by sebastienwozny** [comment]
Pull request created, you can download it here if you can't wait an update :
https://github.com/sebastienwozny/sketch-select/archive/master.zip

**SymbolName** selects all the symbols with same name
**SymbolLayers** selects all symbols

**Comment by mischugo** [comment]
AWESOME!!!
Thank you so much!

**Comment by mischugo** [comment]
Is it possible to have a "Select in all pages" and a "Select in all open documents" option?
This would be ultra productive ... ;-)
